#+ enumerate:
#+   -label

prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix part_of: <http://purl.obolibrary.org/obo/BFO_0000050_SOME>

SELECT DISTINCT ?desc
WHERE {
    ?nucleus rdfs:label ?label .
    ?desc part_of: ?nucleus .
}
